### ISSUE TITLE
Certifiace Error at https://status.evnotify.de/

### ISSUE THREAD

**Issue by stilicrafter** [EVNotify/EVNotify#289]
Hi,
if you try to access https://status.evnotify.de/ you get a cert isue.
Can you take a look at this?
Danke ^^

**Comment by GPlay97** [comment]
The issue has been fixed.

**Comment by cremor** [comment]
@GPlay97 I still can't open that page. Firefox shows an SSL_ERROR_INTERNAL_ERROR_ALERT, Edge an ERR_SSL_PROTOCOL_ERROR

**Comment by GPlay97** [comment]
Ah i See. It is due to the https. It is now a redirect since uptime Robot No longer Supports dns Host for free. If you Access without https it works. It will redirect you to the uptime page
